

### Obtener todas las categorías
GET http://localhost:5000/categorias

### Obtener una categoría por ID
GET http://localhost:5000/categorias/1

### Crear nueva categoría
POST http://localhost:5000/categorias
Content-Type: application/json

{
  "nombre": "Hogar"
}

### Editar categoría existente
PUT http://localhost:5000/categorias/1
Content-Type: application/json

{
  "nombre": "Electrónica "
}

### Eliminar una categoría
DELETE http://localhost:5000/categorias/10

### Obtener todos los productos
GET http://localhost:5000/productos

### Obtener productos disponibles
GET http://localhost:5000/productos/disponible

### Obtener producto por ID
GET http://localhost:5000/productos/1

### Crear nuevo producto
POST http://localhost:5000/productos
Content-Type: application/json


{
  "nombre": "Sensor DHT121",
  "precio": 3.5,
  "descripcion": "Sensor de temperatura y humedad",
  "disponible": false,
  "fecha_ingreso": "2025-07-15T15:00:00.000Z",
  "categoria_id": 1
}

### Actualizar producto existente
PUT http://localhost:5000/productos/5
Content-Type: application/json

{
 "nombre": "Sensor DHT121",
  "precio": 3.5,
  "descripcion": "Sensor de temperatura y humedad",
  "disponible": true,
  "fecha_ingreso": "2025-07-15T15:00:00.000Z",
  "categoria_id": 2
}

### Eliminar producto
DELETE http://localhost:5000/productos/2
